version: '3.7'

services:
  web:
    container_name: whoweb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      # allows fs.watch, fs.watchFile and fsevents
      # allows hot-reloading 
      - CHOKIDAR_USEPOLLING=true 

