name: Deploy React App # name of the workflow
on:
  push:
    branches:
      - main
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
      - 'test/**'
      - 'testing/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-react-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository content to github runner
      - name: Checkout
        uses: actions/checkout@v2

      # setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "18.16.1"

      # cache the dependencies to speed up the build
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # install dependencies
      - name: Install dependencies
        run: npm i

      # build the react app
      - name: Build
        run: npm run build

      #- name: Build and Deploy React app to GitHub Pages
      #  uses: omkartapale/react-deployment-gh-pages@v1.0.0

      # deploy the react app to github pages
      #- name: Deploy (npm)
      #  run: |
      #    git config --global user.name 'github-actions'
      #    git config --global user.email 'github-actions@github.com'
      #    npm run deploy
      #    git --work-tree build add --all
      #    git commit -m "Automatic Build and Deploy run by GitHub Actions"
      #    git push origin HEAD:gh-pages --force
      #  #npm run deploy

      # deploy the react app to github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # NOTE: GITHUB_TOKEN is a secret token that is automatically generated by GitHub
          github_token: ${{ secrets.deploy_key_for_whovisions }} #deploy_key_for_whovisions
          publish_dir: ./build # directory to deploy
          publish_branch: gh-pages # forced branch to publish site
